server:
  port: 3001
  servlet:
    context-path: /api

spring:
  config:
    import: "classpath:application-db.yaml"

  datasource:
    # 실제 값은 별도 파일(application-db.yaml)에서 로딩
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    root: INFO
    com.example.gpu_dashboard: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

# CORS 설정
cors:
  allowed-origins: "http://localhost:3000, *.svc.cluster.local:3000"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600
kubeconfig:
  # path: ./src/main/resources/kube_config.yaml
  path: classpath:kube_config.yaml

# 애플리케이션 관련 커스텀 설정
app:
  jwt:
    secret: your-secret-key-here
    expiration: 86400000  # 24시간
  gpu:
    check-interval: 60000  # GPU 상태 체크 간격 (밀리초)
